### ISSUE TITLE
add Bioverse to PyPI

### ISSUE THREAD

**Issue by matiscke** [danielapai/bioverse#27]
Bioverse should be added to PyPI so it becomes pip-installable.

**Comment by matiscke** [comment]
@vivianaugust thank you for setting up Bioverse on PyPi. Could you add @kevinkhu , @danielapai and me as package maintainers? 

Let's discuss tomorrow what to put as a project description.

**Comment by kevinkhu** [comment]
Tested pip installing Bioverse in a conda environment running Python 3.11. Installed properly, no problems.
