### ISSUE TITLE
setup.py fails due to list[str] command in Python versions <3.9

### ISSUE THREAD

**Issue by JamieDietrich** [danielapai/bioverse#62]
Currently running Python 3.8.8 as my base Python distro, and when I try to "pip install ." or run "python setup.py" it fails on the line "def requirements_list -> list[str]:". Using either 3.9.0 or 3.12.0 in a oonda virtual environment it works just fine.

**Comment by matiscke** [comment]
Good catch, thank you Jamie. There might be a compatibility issue with python versions < 3.9. Would you mind dropping the full error message?

**Comment by JamieDietrich** [comment]
Kevin looked into this yesterday as well and came to the same conclusion, something about the type declaration wasn't supported in versions < 3.9 but was fixed in 3.9+
